Final project/Web_Author/Models/DiemDuLich.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Web_Author.Models
{
    public class DiemDuLich
    {
        [Key]
        public int ID { set; get; }
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        [Display(Name="Tên Địa Điểm")]
        public string TenDiaDiem { set; get; }
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        [Display(Name="Nội Dung")]
        public string NoiDung { set; get; }
        [Display(Name="Hình")]
        public string Hinh { set; get; }
        public DateTime NgayTao { set; get; }
        public int TongLike { set; get; }
        public int TongCmt { set; get; }
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        [Display(Name="Tên Miền(Bắc/Trung/Nam)")]
        public string Mien { set; get; }
        [Display(Name = "Đường dẫn video")]
        public string Video { set; get; }
        public virtual ICollection<CmtDiemDuLich> CmtDiemDuLich { set; get; }
        public virtual ICollection<LikeDiemDuLich> LikeDiemDLich { set; get; }
    }
}

Final project/Web_Author/Controllers/CmtDiemDuLichController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_Author.Models;

namespace Web_Author.Controllers
{
    public class CmtDiemDuLichController : Controller
    {
        private WebDbContext db = new WebDbContext();

        //
        // GET: /CmtDiemDuLich/

        public ActionResult Index()
        {
            var cmtdiemduliches = db.CmtDiemDuLiches.Include(c => c.DiemDuLich);
            return View(cmtdiemduliches.ToList());
        }

        //
        // GET: /CmtDiemDuLich/Details/5

        public ActionResult Details(int id = 0)
        {
            CmtDiemDuLich cmtdiemdulich = db.CmtDiemDuLiches.Find(id);
            if (cmtdiemdulich == null)
            {
                return HttpNotFound();
            }
            return View(cmtdiemdulich);
        }

        //
        // GET: /CmtDiemDuLich/Create

        public ActionResult Create()
        {
            ViewBag.DiemDuLichID = new SelectList(db.DiemDuLiches, "ID", "TenDiaDiem");
            return View();
        }

        //
        // POST: /CmtDiemDuLich/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CmtDiemDuLich cmtdiemdulich,int idDiemDuLich)
        {
            var diemdulich = (from n in db.DiemDuLiches
                              where n.ID == idDiemDuLich
                              select n).Single();
            
            //cmtdiemdulich.DiemDuLich = id;
            cmtdiemdulich.AccID = LuuTrangThai.ID;
            cmtdiemdulich.Ten = LuuTrangThai.Name;
            cmtdiemdulich.DiemDuLichID = idDiemDuLich;
 
            db.CmtDiemDuLiches.Add(cmtdiemdulich);
            diemdulich.TongCmt++;
            db.Entry(diemdulich).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Details/"+idDiemDuLich,"DiemDuLich");

           // ViewBag.DiemDuLichID = new SelectList(db.DiemDuLiches, "ID", "TenDiaDiem", cmtdiemdulich.DiemDuLichID);
           // return View(cmtdiemdulich);
        }

        //
        // GET: /CmtDiemDuLich/Edit/5

        public ActionResult Edit(int id = 0)
        {
            CmtDiemDuLich cmtdiemdulich = db.CmtDiemDuLiches.Find(id);
            if (cmtdiemdulich == null)
            {
                return HttpNotFound();
            }
            ViewBag.DiemDuLichID = new SelectList(db.DiemDuLiches, "ID", "TenDiaDiem", cmtdiemdulich.DiemDuLichID);
            return View(cmtdiemdulich);
        }

        //
        // POST: /CmtDiemDuLich/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CmtDiemDuLich cmtdiemdulich)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cmtdiemdulich).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DiemDuLichID = new SelectList(db.DiemDuLiches, "ID", "TenDiaDiem", cmtdiemdulich.DiemDuLichID);
            return View(cmtdiemdulich);
        }

        //
        // GET: /CmtDiemDuLich/Delete/5

        public ActionResult Delete(int id = 0)
        {
            CmtDiemDuLich cmtdiemdulich = db.CmtDiemDuLiches.Find(id);
            if (cmtdiemdulich == null)
            {
                return HttpNotFound();
            }
            return View(cmtdiemdulich);
        }

        //
        // POST: /CmtDiemDuLich/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CmtDiemDuLich cmtdiemdulich = db.CmtDiemDuLiches.Find(id);
            db.CmtDiemDuLiches.Remove(cmtdiemdulich);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Final project/Web_Author/Controllers/DiemDuLichController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_Author.Models;

namespace Web_Author.Controllers
{
    public class DiemDuLichController : Controller
    {
        LikeDiemDuLich ss = new LikeDiemDuLich();
        
        private WebDbContext db = new WebDbContext();

        //
        // GET: /DiemDuLich/
        public ActionResult DiemDuLich()
        {
           
            string Chuoi3 = "";
            Chuoi3 += "Xin chào ";
            string Chuoi4 = LuuTrangThai.Name.ToString();
            ViewBag.View2 = Chuoi3;
            ViewBag.View3 = Chuoi4;
            string Noidung = "";
            var a = from nd in db.DiemDuLiches.OrderByDescending(x => x.NgayTao)
                          select nd;
            foreach(var b in a)
            {
                
                Noidung += "<div class=\"khungdiemdulich\">";
                Noidung += "<div class=\"diemdulich-post-noidung\">";
                Noidung += "<h3 style=\"margin:0px;padding:0px\">"+b.TenDiaDiem+"</h3>";
                Noidung += "<div>";
                Noidung += "<img src=\""+b.Hinh+"\" style=\"width:400px;height:100px\"/>";
                Noidung += "</div>";
                Noidung += "<div>";
                Noidung += b.NoiDung;
                Noidung += "</div>";

                Noidung += "</div>";
                Noidung += "<div class=\"diemdulich-post-video\">";
                Noidung += "<h3 style=\"margin:0px;padding:0px\">Giới thiệu về " + b.TenDiaDiem + "</h3>";
                Noidung += "<iframe width=\"440px\" height=\"220px\" src=\"" + b.Video + "\" allowfullscreen></iframe>";
                Noidung += "</div>";

                Noidung += "<div class=\"like-cmt\">";
                Noidung += "<a href=\"http://localhost:2517/diemdulich/details/" + b.ID + "\" >";
                Noidung += "Nhấn vào đây để bình luận, đánh giá.";
                Noidung += "</a>";
                
                //Noidung += "<input id=\"Like\" style=\"float:left\" type=\"submit\" value=\"Thích\" onclick=\"BrowseServer();\" />";
                //Noidung += "<input id=\"Comment\" style=\"float:left;margin-left:50px\" type=\"button\" value=\"Bình luận\" onclick=\"BrowseServer();\" />";
                Noidung += "</div>";
                Noidung+="<input type=\"hidden\" id=\""+b.ID+"\"/>";
                Noidung += "</div>";

            }
            ViewBag.NoiDung = Noidung;
            return View();
            
        }
        public ActionResult Index()
        {
            return View(db.DiemDuLiches.ToList());
        }

        //
        // GET: /DiemDuLich/Details/5

        public ActionResult Details(int id = 0)
        {

            string Noidung = "";
            DiemDuLich diemdulich = db.DiemDuLiches.Find(id);
            int like = (from n in db.LikeDiemDuLiches
                        where (n.Account.AccID == LuuTrangThai.ID && n.DiemDuLich.ID == diemdulich.ID)
                        select n).Count(); 
            if (diemdulich == null)
            {
                return HttpNotFound();
            }
            Noidung += "<div class=\"khungdiemdulich\">";
            Noidung += "<div class=\"diemdulich-post-noidung\">";
            Noidung += "<h3 style=\"margin:0px;padding:0px\">" + diemdulich.TenDiaDiem + "</h3>";
            Noidung += "<div>";
            Noidung += "<img src=\"" + diemdulich.Hinh + "\" style=\"width:400px;height:100px\"/>";
            Noidung += "</div>";
            Noidung += "<div>";
            Noidung += diemdulich.NoiDung;
            Noidung += "</div>";

            Noidung += "</div>";
            Noidung += "<div class=\"diemdulich-post-video\">";
            Noidung += "<h3 style=\"margin:0px;padding:0px\">Giới thiệu về " + diemdulich.TenDiaDiem + "</h3>";
            Noidung += "<iframe width=\"440px\" height=\"220px\" src=\"" + diemdulich.Video + "\" allowfullscreen></iframe>";
            Noidung += "</div>";

            Noidung += "<div class=\"like-cmt\">";
            if(like==0)
                Noidung += "<input type=\"submit\" value=\"Thích\" style=\"float:left\" />";
            else
                Noidung += "<input type=\"submit\" value=\"Bỏ thích\"style=\"float:left\" />"; 
            //Noidung += "<input id=\"Comment\" style=\"float:left;margin-left:50px\" type=\"button\" value=\"Bình luận\" onclick=\"BrowseServer();\" />";
            Noidung += "</div>";
            Noidung += "<input type=\"hidden\" id=\"" + diemdulich.ID + "\"/>";
            Noidung += "</div>";
            ViewBag.NoiDung = Noidung;
            ViewData["idDiemDuLich"] = diemdulich.ID;
            return View(diemdulich);
        }

        //
        // GET: /DiemDuLich/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details(LikeDiemDuLich like,int id=0)
        {
            
            DiemDuLich diemdulich = db.DiemDuLiches.Find(id);
            var like2 = (from n in db.LikeDiemDuLiches
                         where (n.Account.AccID == LuuTrangThai.ID && n.DiemDuLich.ID == diemdulich.ID)
                         select n);
            int like1 = like2.Count();
            if(like1==0)
            {
                diemdulich.TongLike++;
                like.Account = db.Accounts.Find(LuuTrangThai.ID);
                like.DiemDuLich = diemdulich;
                like.AccID = LuuTrangThai.ID;
                like.DiemDuLichID = diemdulich.ID;
                db.LikeDiemDuLiches.Add(like);
                db.SaveChanges();
            }
            else
            {
                diemdulich.TongLike--;
                db.LikeDiemDuLiches.Remove(like2.Single());
                db.SaveChanges();
            }
            db.Entry(diemdulich).State = EntityState.Modified;
            return Details(diemdulich.ID);
        }
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /DiemDuLich/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DiemDuLich diemdulich)
        {
            diemdulich.TongLike = 0;
            diemdulich.TongCmt = 0;
            diemdulich.NgayTao = DateTime.Now;
            diemdulich.Hinh = diemdulich.Hinh;
   
            {
                db.DiemDuLiches.Add(diemdulich);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //return View(diemdulich);
        }

        //
        // GET: /DiemDuLich/Edit/5

        public ActionResult Edit(int id = 0)
        {
            DiemDuLich diemdulich = db.DiemDuLiches.Find(id);
            if (diemdulich == null)
            {
                return HttpNotFound();
            }
            return View(diemdulich);
        }

        //
        // POST: /DiemDuLich/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DiemDuLich diemdulich)
        {
            if (ModelState.IsValid)
            {
                db.Entry(diemdulich).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(diemdulich);
        }

        //
        // GET: /DiemDuLich/Delete/5

        public ActionResult Delete(int id = 0)
        {
            DiemDuLich diemdulich = db.DiemDuLiches.Find(id);
            if (diemdulich == null)
            {
                return HttpNotFound();
            }
            return View(diemdulich);
        }

        //
        // POST: /DiemDuLich/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DiemDuLich diemdulich = db.DiemDuLiches.Find(id);
            db.DiemDuLiches.Remove(diemdulich);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Final project/Web_Author/Views/DiemDuLich/AddCmtDiemDuLich.cshtml
@model Web_Author.Models.CmtDiemDuLich


@using (Html.BeginForm("Create", "CmtDiemDuLich", new { idDiemDuLich = ViewData["idDiemDuLich"] }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>


        <div class="editor-label">
           Nhập nội dung
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NoiDung)
            @Html.ValidationMessageFor(model => model.NoiDung)
        </div>


        <p>
            <input type="submit" value="Bình luận" />
        </p>
    </fieldset>
}

Final project/Web_Author/Views/DiemDuLich/Create.cshtml
@model Web_Author.Models.DiemDuLich

@{
    ViewBag.Title = "Create";
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Content/ckfinder/ckfinder.js"></script>
    <script src="~/Content/ckeditor/ckeditor.js"></script>
}

<h2>Create</h2>
<script src="../../Scripts/ckfinder/ckfinder.js"></script>
<script type="text/javascript">
    function BrowseServer() {
        var finder = new CKFinder();
        //finder.basePath = '../';
        finder.selectActionFunction = SetFileField;
        finder.popup();
    }
    function SetFileField(fileUrl) {
        document.getElementById('Hinh').value = fileUrl;
        $('#myImg').attr('src', fileUrl);
    }
</script>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>DiemDuLich</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.TenDiaDiem)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TenDiaDiem)
            @Html.ValidationMessageFor(model => model.TenDiaDiem)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NoiDung)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NoiDung)
            @Html.ValidationMessageFor(model => model.NoiDung)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Hinh)
        </div>
        <div class="editor-field">
            <input id="Browser" type="button" value="Chọn Ảnh ..." onclick="BrowseServer();" />
            @Html.HiddenFor(model => model.Hinh)


            @Html.ValidationMessageFor(model => model.Hinh)

        </div>
        <img id="myImg" src="" alt="your image" style="width:200px;height:100px" />
        <div class="editor-label">
            @Html.LabelFor(model => model.Video)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Video)
            @Html.ValidationMessageFor(model => model.Video)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Mien)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Mien)
            @Html.ValidationMessageFor(model => model.Mien)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Final project/Web_Author/Views/DiemDuLich/Delete.cshtml
@model Web_Author.Models.DiemDuLich

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>DiemDuLich</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TenDiaDiem)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TenDiaDiem)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NoiDung)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NoiDung)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Hinh)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Hinh)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NgayTao)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NgayTao)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TongLike)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TongLike)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TongCmt)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TongCmt)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Mien)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Mien)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Final project/Web_Author/Views/DiemDuLich/Details.cshtml
@model Web_Author.Models.DiemDuLich

@{
    ViewBag.Title = "Điểm du lịch";
}

<h2>Thông tin du lịch</h2>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
<fieldset>
    <legend>Điểm du lịch</legend>

    @*<div class="display-label">
         @Html.DisplayNameFor(model => model.TenDiaDiem)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TenDiaDiem)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NoiDung)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NoiDung)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Hinh)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Hinh)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NgayTao)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NgayTao)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TongLike)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TongLike)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TongCmt)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TongCmt)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Mien)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Mien)
    </div>*@
    @Html.Raw(ViewBag.NoiDung)
</fieldset>
}
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")*@
</p>
<fieldset>
    <legend>Bình luận</legend>
    @foreach(var a in Model.CmtDiemDuLich)
    {
       <div class="display-field">
           <a style="font-size:large;font-style:oblique">@Html.DisplayFor(x=>a.Ten)</a>:
           @Html.DisplayFor(x => a.NoiDung)
       </div>
    }
</fieldset>
@Html.Partial("AddCmtDiemDuLich", new Web_Author.Models.CmtDiemDuLich(), ViewData);

Final project/Web_Author/Views/DiemDuLich/DiemDuLich.cshtml
@{
    ViewBag.Title = "Điểm du lịch";
}
<link rel="stylesheet" type="text/css" href="ddlevelsfiles/ddlevelsmenu-base.css" />
<link rel="stylesheet" type="text/css" href="ddlevelsfiles/ddlevelsmenu-topbar.css" />
<link rel="stylesheet" type="text/css" href="ddlevelsfiles/ddlevelsmenu-sidebar.css" />
<script src="~/Scripts/ddlevelsmenu.js"></script>
<script type="text/javascript">
    ddlevelsmenu.setup("a", "topbar") //ddlevelsmenu.setup("mainmenuid", "topbar|sidebar")
</script>
<div id="a" class="mattblackmenu" style="font-size:large">
    <ul>
        <li>
            <a href="http://localhost:2517/login/trangchu">
                Trang chủ
            </a>

        </li>
        <li style="list-style:none;">
            <a href="http://localhost:2517/login/trangchu" rel="ddsubmenu1">
                Điểm du lịch
            </a>

        </li>
        <li style="list-style:none;">
            <a href="http://localhost:2517/login/trangchu">
                Đăng kí du lịch
            </a>
        </li>
        <li style="list-style:none;">
            <a href="http://localhost:2517/login/trangchu">
                Thảo luận
            </a>
        </li>
        <li style="list-style:none;">
            <a href="#" rel="ddsubmenu2">
                Đóng góp
            </a>
        </li>

    </ul>
</div>
<ul id="ddsubmenu1" class="ddsubmenustyle">
    <li><a href="http://localhost:2517/Diemdulich/diemdulich">Địa điểm chính</a></li>
    <li><a href="#">Địa điểm được đề xuất</a></li>
</ul>
<ul id="ddsubmenu2" class="ddsubmenustyle">
    <li><a target=" _blank" href=" http://localhost:2517/DongGopYKien" >Đóng góp ý kiến</a></li>
    <li><a href="#">Đề xuất địa điểm</a></li>
</ul>
<div style="float:right">

    @Html.Raw(ViewBag.View2)

    <a target="_blank" href="http://localhost:2517/account/details">@Html.Raw(ViewBag.View3)</a>
</div>
<h1>Điểm du lịch</h1>
<div class="diemdulich">
    <div class="diemdulich-vung">
        <h2>Du lịch vùng</h2>
        <div>
            <h3>@Html.ActionLink("Miền Bắc", "", "")</h3>
        </div>
        <div>
            <h3> @Html.ActionLink("Miền Trung", "", "")</h3>
        </div>
        <div>
            <h3> @Html.ActionLink("Miền Nam", "", "")</h3>
        </div>
    </div>
    <div class="diemdulich-post" >
            @Html.Raw(ViewBag.NoiDung)

    </div>
</div>

Final project/Web_Author/Views/DiemDuLich/Edit.cshtml
@model Web_Author.Models.DiemDuLich

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>DiemDuLich</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.TenDiaDiem)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TenDiaDiem)
            @Html.ValidationMessageFor(model => model.TenDiaDiem)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NoiDung)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NoiDung)
            @Html.ValidationMessageFor(model => model.NoiDung)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Hinh)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Hinh)
            @Html.ValidationMessageFor(model => model.Hinh)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NgayTao)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NgayTao)
            @Html.ValidationMessageFor(model => model.NgayTao)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TongLike)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TongLike)
            @Html.ValidationMessageFor(model => model.TongLike)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TongCmt)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TongCmt)
            @Html.ValidationMessageFor(model => model.TongCmt)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Mien)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Mien)
            @Html.ValidationMessageFor(model => model.Mien)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Video)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Video)
            @Html.ValidationMessageFor(model => model.Video)
        </div>
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Final project/Web_Author/Views/DiemDuLich/Index.cshtml
@model IEnumerable<Web_Author.Models.DiemDuLich>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>

    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TenDiaDiem)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoiDung)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NgayTao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TongLike)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TongCmt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mien)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Video)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TenDiaDiem)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NoiDung)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Hinh)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgayTao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TongLike)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TongCmt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Mien)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Video)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>